### ISSUE TITLE
Error in creating docker container

### ISSUE THREAD

**Issue by itsmeyijie** [FermiSummerSchool/FermiBottle#3]
![image](https://user-images.githubusercontent.com/25410808/46568807-d9fafe00-c97d-11e8-9caa-59d42284fc89.png)

Hello, I found an error while creating docker container showed in the picture, could you please help?

**Comment by itsmeyijie** [comment]
C:\WINDOWS\system32>docker run --init -it \
docker: invalid reference format.
Hello, I found an error while creating docker container above, could you please help?

**Comment by Areustle** [comment]
Run a version of this command instead. Change the `<path to data>` string to the correct path for your personal computer: `docker run --init -it -e DISPLAY=$DISPLAY -v '<path to data>:/data' -p 8888:8888 fssc/fermibottle`

The "`\`" character after `-it` is meant to escape the newline character and let the full command span several lines. If the rest of the full command was not given you will get the error that you report.
